- name: copying sql script fron spec app
  copy:
    src: "../microservices/spec-ms/src/db/"
    dest: "../microservices/postgres-ms"
    owner: "{{ system_user_name }}"
    group: "{{ system_user_name }}"  
  tags: [ install, update ] 
