- name: Generating program selection csv file
  template:
    src: program_selector.csv.j2
    dest: "../microservices/query-builder/program_selector.csv"
    mode: "0644"
  tags: [ install, update ]
