---
- include_tasks: configure_base_dir.yml
  tags: [install, update ]

- include_tasks: configure_compose.yml
  tags: [install, update ]

- include_tasks: configure_program_selector.yml
  tags: [ install, update ]  

- include_tasks: keycloak.yml
  tags: [ install, update ]

