---
- name: Creating config file
  file:
    path: "{{ base_dir }}/cqube/.cqube_config"
    state: touch
    mode: u+rw,g+rw,o+rw
  tags: install

     
- name: Loading required data inside config file
  blockinfile:
        path: "{{ base_dir }}/cqube/.cqube_config"
        block: |
               CQUBE_VERSION={{ cqube_version }}
  tags: install
  
- name: Updating the CQUBE_VERSION
  lineinfile: 
    regex: '^CQUBE_VERSION='
    line: CQUBE_VERSION={{ cqube_version }}
    path: "{{ base_dir }}/cqube/.cqube_config"
  tags: update
