- name: copying database config to generator folder (aws storage)
  template:
    src: config.ini_pg_aws.j2
    dest: "../microservices/generator-ms/static_processor_group/config.ini"
  when: storage_type == "aws"
  tags: [ install, update ]

- name: copying database config to generator folder (local storage)
  template:
    src: config.ini_pg_local.j2
    dest: "../microservices/generator-ms/static_processor_group/config.ini"
  when: storage_type == "local"
  tags: [ install, update ]

- name: copying database config to generator folder (azure storage)
  template:
    src: config.ini_pg_azure.j2
    dest: "../microservices/generator-ms/static_processor_group/config.ini"
  when: storage_type == "azure"
  tags: [ install, update ]

- name: copying database config to generator folder (oracle storage)
  template:
    src: config.ini_pg_oracle.j2
    dest: "../microservices/generator-ms/static_processor_group/config.ini"
  when: storage_type == "oracle"
  tags: [ install, update ]
  
