- name: copying database config to generator folder
  template:
    src: config.ini.j2
    dest: "../microservices/spec-ms/python/transformer_generator/transformers/config.ini"
  tags: [ install, update ]
