---
- hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - ../config.yml
  tasks:
    - name: docker compose
      become_user: "{{ system_user_name }}"
      community.docker.docker_compose:
        project_src: .
