---
- name: Installing cQube
  hosts: localhost
  gather_facts: true
  remote_user: root
  become: true
  vars_files:
    - ../config.yml

  roles:
          - configurations
          - postgres 
          - python
          - ingestion
          - spec
          - generator
          - dashboard
          - nifi
          - nginx
