---
- name: Running docker compose
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - ../config_files/upgradation_config.yml
    - ../config_files/upgradation_azure_container_config.yml
    - ../config_files/upgradation_aws_s3_config.yml
    - ../config_files/upgradation_local_storage_config.yml
    - ../config_files/upgradation_oracle_storage_config.yml

  roles:
         - compose
