---
- name: Upgradting cQube
  hosts: localhost
  gather_facts: true
  remote_user: root
  become: true
  vars_files:
    - ../upgradation_config.yml
    - ../upgradation_azure_container_config.yml
    - ../upgradation_aws_s3_config.yml
    - ../upgradation_local_storage_config.yml
    - ../program_selector.yml

  roles:
          - configurations
          - postgres 
          - python
          - ingestion
          - spec
          - generator
          - dashboard
          - querybuilder
          - nifi
          - nginx
