- name: copying dockerfile script to ingestion repository
  template:
    src: Dockerfile.j2
    dest: "../microservices/ingestion-ms/Dockerfile"
    mode: "0644"  
  tags: [ install, update ]

- name: Creating environmental variables
  file:
    path: ../microservices/ingestion-ms/.env
    state: touch
    mode: u+rw,g+rw,o+rw
  tags: [ install, update ]

- name: Loading required data inside .env file
  blockinfile:
    path: ../microservices/ingestion-ms/.env
    block: |
      DB_HOST = 'postgres_app'
      DB_PORT = 5432
      DB_USERNAME = "{{ db_user }}"
      DB_PASSWORD = "{{ db_password }}"
      DB_NAME = "{{ db_name }}"
      NIFI_IP = 'nifi_app'
      NIFI_PORT = 8096
      URL = "http://{{ api_endpoint }}"
      WRK_DIR_PYTHON = '/generator_data/transformer_generator/transformers/python_files'
      PYTHON_PATH = '/usr/bin/python3.7'
      FLASKAPI = 'http://generator_app'
      FLASK_PORT = 3003
      AWS_ACCESS_KEY = "{{ aws_access_key }}"
      AWS_SECRET_KEY = "{{ aws_secret_key }}"
      ARCHIVED_BUCKET= "{{ s3_archived_bucket }}"
      ERROR_BUCKET= "{{ s3_error_bucket }}"
