- name: Check if nifi is present in destination
  stat:
    path: "{{ base_dir }}/cqube/nifi/nifi"
  register: status
  tags: update

- name: stop nifi if its running
  ansible.builtin.shell: "{{ base_dir }}/cqube/nifi/nifi/bin/nifi.sh stop"
  when: status.stat.exists == true
  tags: update

- name: remove cQube directory if present
  become: yes
  ansible.builtin.shell: rm -rf {{ base_dir }}/cqube
  ignore_errors: yes
  args:
    warn: false
  tags: update

- name: Stop PM2 service
  become: true
  shell: pm2 stop all
  tags: update

- name: Stop PM2 service
  become: true
  shell: pm2 delete all           
  tags: update  

- name: Stop postgre.service
  systemd:
    name: postgresql.service
    state: stopped
  tags: update
  
- name: Stop postgre.service
  systemd:
    name: keycloak.service
    state: stopped
  tags: update 

- name: Stop postgre.service
  systemd:
    name: prometheus.service
    state: stopped
  tags: update 

- name: Stop postgre.service
  systemd:
    name: grafana-server.service
    state: stopped
  tags: update 

- name: Stop postgre.service
  systemd:
    name: kong.service
    state: stopped
  tags: update
   
- name: Stop postgre.service
  systemd:
    name: node_exporter.service
    state: stopped
  tags: update
